base_url = "https://www.kentbull.com"
author = "Kent Bull"
title = "Kent Bull Blog"
description = "Decentralized identity, software development, and local governance focused blog."
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
default_language = "en"

theme = "apollo"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"


[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark",  filename = "syntax-theme-dark.css"  },
  { theme = "ayu-light", filename = "syntax-theme-light.css" }
]


[extra]
toc = true
use_cdn = false
favicon = "favicon.ico"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_view = true
repo_url = "https://github.com/kentbull/kent_bull_blog/tree/main/content/"


socials = [
    { name = "twitter",  url = "https://twitter.com/kentbull",        icon = "twitter"  },
    { name = "github",   url = "https://github.com/kentbull/",        icon = "github"   },
    { name = "linkedin", url = "https://www.linkedin.com/in/kobull/", icon = "linkedin" },
]
menu = [
  { name = "/posts",    url= "/posts",    weight = 1 },
  { name = "/projects", url= "/projects", weight = 2 },
  { name = "/talks",    url= "/talks",    weight = 3 },
  { name = "/tags",     url= "/tags",     weight = 4 },
]

stylesheets = [
    "custom.css",
]
[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "kentbull"
host = "goatcounter.com"




